persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Isso permite que o ESP32 conecte sem senha e de fora do container
listener 1883 0.0.0.0

allow_anonymous true

